title: GIL Morgan - Développeur Back
description: Le blog d'un développeur libro-phpiste

url: https://gilmorgan.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: gilmorgan
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: gilmorgan.pro@gmail.com

google_analytics: ""
